######################################################################
##
## Filename: example_file_io_tb.udo
## Created on: Fri May 12 17:22:04 Romance Summer Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
