######################################################################
##
## Filename: filehandle.udo
## Created on: Fri May 12 17:13:37 Romance Summer Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
