######################################################################
##
## Filename: TB_board.udo
## Created on: Wed May 24 16:16:21 Romance Summer Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
